# Generated by Django 6.1.1 on 2026-09-20 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('live', 'Live capture'), ('file', 'Uploaded PCAP')], max_length=8)),
                ('interface', models.CharField(blank=True, help_text='Capture interface name, only set for live sessions.', max_length=100)),
                ('original_filename', models.CharField(blank=True, help_text='Original PCAP filename, only set for file sessions.', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(choices=[('DNS', 'DNS'), ('HTTP', 'HTTP'), ('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ARP', 'ARP'), ('OTHER', 'Other')], max_length=8)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('byte_count', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='netcap.capturesession')),
            ],
            options={
                'ordering': ['-byte_count'],
                'constraints': [models.UniqueConstraint(fields=('session', 'src_ip', 'dst_ip', 'protocol'), name='unique_conversation_per_session')],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_local', models.BooleanField(default=False, help_text='True for the machine running the capture')),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('byte_count', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='netcap.capturesession')),
            ],
            options={
                'ordering': ['-byte_count'],
                'constraints': [models.UniqueConstraint(fields=('session', 'ip_address'), name='unique_host_per_session')],
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('src_mac', models.CharField(blank=True, max_length=17)),
                ('dst_mac', models.CharField(blank=True, max_length=17)),
                ('ethertype', models.CharField(blank=True, max_length=10)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.PositiveIntegerField(blank=True, null=True)),
                ('dst_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('DNS', 'DNS'), ('HTTP', 'HTTP'), ('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ARP', 'ARP'), ('OTHER', 'Other')], max_length=8)),
                ('ip_protocol_number', models.PositiveSmallIntegerField(blank=True, help_text='Raw IP protocol number (6=TCP, 17=UDP, ...)', null=True)),
                ('length', models.PositiveIntegerField(help_text='Total frame length in bytes')),
                ('encrypted', models.BooleanField(default=False)),
                ('info', models.CharField(blank=True, help_text='One-line human-readable summary', max_length=255)),
                ('payload_preview', models.CharField(blank=True, help_text='Truncated, safe preview of the payload (see settings.MESHVIEW_PAYLOAD_PREVIEW_BYTES)', max_length=256)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='netcap.capturesession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='netcap_pack_session_2fd52c_idx'), models.Index(fields=['session', 'protocol'], name='netcap_pack_session_47aca9_idx'), models.Index(fields=['session', 'src_ip'], name='netcap_pack_session_e77d3d_idx'), models.Index(fields=['session', 'dst_ip'], name='netcap_pack_session_e9f3ac_idx'), models.Index(fields=['session', 'src_port'], name='netcap_pack_session_3b3c3b_idx'), models.Index(fields=['session', 'dst_port'], name='netcap_pack_session_6cc661_idx')],
            },
        ),
    ]
