# Generated by Django 6.1.1 on 2026-09-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='encrypted',
            field=models.BooleanField(default=False, help_text='True if any packet in this conversation was classified as encrypted'),
        ),
    ]
